#!/usr/bin/env php
<?php

/**
 * Copyright (c) anno Domini nostri Jesu Christi MMXXVI, John Boehr & contributors
 *
 * SPDX-License-Identifier: AGPL-3.0-only WITH romic-exception
 */

declare(strict_types=1);

const IDENTIFIER_PATTERN = '/\A[\p{L}\p{Nd}]\z/uD';
const DECIMAL_DIGIT_PATTERN = '/\A\p{Nd}\z/uD';
const WHITESPACE_PATTERN = '/\A\s\z/uD';

/** @return non-empty-string */
function encodeCodePoint(int $codePoint): string
{
    if ($codePoint <= 0x7f) {
        return chr($codePoint);
    }
    if ($codePoint <= 0x7ff) {
        return chr(0xc0 | ($codePoint >> 6))
            . chr(0x80 | ($codePoint & 0x3f));
    }
    if ($codePoint <= 0xffff) {
        return chr(0xe0 | ($codePoint >> 12))
            . chr(0x80 | (($codePoint >> 6) & 0x3f))
            . chr(0x80 | ($codePoint & 0x3f));
    }

    return chr(0xf0 | ($codePoint >> 18))
        . chr(0x80 | (($codePoint >> 12) & 0x3f))
        . chr(0x80 | (($codePoint >> 6) & 0x3f))
        . chr(0x80 | ($codePoint & 0x3f));
}

/**
 * @return list<array{int, int}>
 */
function collectRanges(string $pattern): array
{
    $ranges = [];
    $rangeStart = null;
    $previous = null;

    for ($codePoint = 0; $codePoint <= 0x10ffff; ++$codePoint) {
        if ($codePoint >= 0xd800 && $codePoint <= 0xdfff) {
            continue;
        }

        $matches = preg_match($pattern, encodeCodePoint($codePoint)) === 1;
        if ($matches) {
            $rangeStart ??= $codePoint;
            $previous = $codePoint;
        } elseif ($rangeStart !== null) {
            $ranges[] = [$rangeStart, $previous];
            $rangeStart = null;
            $previous = null;
        }
    }

    if ($rangeStart !== null) {
        $ranges[] = [$rangeStart, $previous];
    }

    return $ranges;
}

/**
 * @param list<array{int, int}> $ranges
 */
function renderRanges(string $name, array $ranges): string
{
    $output = "static const yumemi_unicode_range yumemi_unicode_{$name}_ranges[] = {\n";
    foreach ($ranges as [$first, $last]) {
        $output .= sprintf("    {0x%06xu, 0x%06xu},\n", $first, $last);
    }
    $output .= "};\n\n";
    $output .= sprintf(
        "#define YUMEMI_UNICODE_%s_RANGE_COUNT \\\n    (sizeof(yumemi_unicode_%s_ranges) / sizeof(yumemi_unicode_%s_ranges[0]))\n",
        strtoupper($name),
        $name,
        $name,
    );

    return $output;
}

$identifierRanges = collectRanges(IDENTIFIER_PATTERN);
$decimalDigitRanges = collectRanges(DECIMAL_DIGIT_PATTERN);
$whitespaceRanges = collectRanges(WHITESPACE_PATTERN);
$pcreVersion = PCRE_VERSION;
$cPcreVersion = addcslashes($pcreVersion, '\\"');

$content = <<<HEADER
/**
 * Generated by scripts/generate-unicode-ranges.php using PCRE {$pcreVersion}.
 * Do not edit manually.
 *
 * SPDX-License-Identifier: AGPL-3.0-only WITH romic-exception
 */

#ifndef PHP_YUMEMI_UNICODE_RANGES_H
#define PHP_YUMEMI_UNICODE_RANGES_H

#define YUMEMI_UNICODE_PCRE_VERSION "{$cPcreVersion}"

typedef struct {
    uint32_t first;
    uint32_t last;
} yumemi_unicode_range;

HEADER;
$content .= renderRanges('identifier', $identifierRanges);
$content .= renderRanges('decimal_digit', $decimalDigitRanges);
$content .= renderRanges('whitespace', $whitespaceRanges);
$content .= "\n#endif /* PHP_YUMEMI_UNICODE_RANGES_H */\n";

$outputPath = dirname(__DIR__) . '/src/parser/unicode_ranges.h';
$check = in_array('--check', $argv, true);

if ($check) {
    $current = is_file($outputPath) ? file_get_contents($outputPath) : false;
    if ($current !== $content) {
        fwrite(STDERR, "Generated Unicode ranges are out of date.\n");
        exit(1);
    }
    exit(0);
}

if (file_put_contents($outputPath, $content) === false) {
    fwrite(STDERR, "Unable to write {$outputPath}.\n");
    exit(1);
}
